receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers:  [otlp]
      exporters:  [logging]
    metrics:
      receivers:  [otlp]
      exporters:  [prometheus]
