apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "software3-lab.fullname" . }}
  labels:
    {{- include "software3-lab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "software3-lab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "software3-lab.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: software3-lab
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
